let x=5;;
let x=6 in x*x;;
x;;
x=4;;
(* let x=3 in let y=x+3;; *) (* code erronne car dans in il faut une expression *)
let y=let x=3in x+3;;
let f=fun x y z->x+y+z;;
f 1 2 3;;
let f= function x->x+2;;
f 5;;
(f 5);;
let g x=x+2;;
g 5;;
g 3*7;;
g (3*7);;
let val_abs= if x<0 then -x else x;;
let f2=fun x y->let z=x-y in if z>0 then z else x;;
f2 3 8;;
f2 9 2;;
let f3 x y=let z=x*x in let w=z-y in if w>0 then w else z;;
f3 5 2;;
f3 2 13;;
let f4 = f3 5;;
f4 2;;
let f5 x =f3 x 13;;
f5 2;;
let f_3 (x,y)=f3 x y;;
f_3 (5,2);;
let f4 x =f_3 (5,x);;
let f5 x=f_3(x,13);;
let subfg f g x= f x -g x;;
subfg f g x where f x=x*x and g x=x-1 and x=a+2 where a=4;;
subfg (fun x->x*x) (fun x->x-1) (a+2) where a=4;;
let curry f x y=f(x,y);;
let uncurry f (x,y)=f x y;;
